### ISSUE TITLE
Evaluate the two bot PR (npm udpate)

### ISSUE THREAD

**Issue by fabfabBesnard** [romi/3d-plantviewer#110]

**Comment by gregho67** [comment]
Both the branches allow to launch the app, however it seems like opening certain datasets (plants) throws a javascript error.
The error I received were these : 
![Screenshot from 2021-06-08 12-17-39](https://user-images.githubusercontent.com/85161471/121169461-52639c80-c854-11eb-9cd8-a2a4ef436c93.png)
![Screenshot from 2021-06-08 12-19-12](https://user-images.githubusercontent.com/85161471/121169463-52fc3300-c854-11eb-9a97-5637c3c46db0.png)
I got these errors when I tried to open a dataset with a plant reconstruction and with automatic and manual measures.

I don't think that it's useful to merge these branches with master since the app is working fine without the updates, and because it may cause errors when trying to open certain datasets
